/**
* @package		Breizh Shoutbox extension
* @copyright(c)	2018-2021 Sylver35  https://breizhcode.com
* @license		http://opensource.org/licenses/gpl-license.php GNU Public License
*/
/** global: config,global: bzhLang,global: shoutbox */
var tpl=[],uastring=navigator.userAgent,index,navigateur,version,is_ie=-1!=uastring.indexOf("msie")&&-1==uastring.indexOf("opera"),headersContent={"Cache-Control":"private, no-cache, no-store, must-revalidate, proxy-revalidate",Pragma:"no-cache"},dataRun="user="+config.userId+"&sort="+config.sortShoutNb,timerIn,timerOnline,timerCookies,onCount=0,$queryNb=0,first=!0,form_name="postform",text_name="chat_message",imgChargeOn='<img src="'+config.extensionUrl+'images/run.gif" alt="" style="margin-right:15px;" />',
imgLoadOn='<img src="'+config.extensionUrl+'images/run2.gif" alt="" style="margin-right:15px;" />',imgTurnOn='<img src="'+config.extensionUrl+'images/spinner.gif" alt="" style="margin-right:15px;" />',ajaxLoaderOn='<img src="'+config.extensionUrl+'images/ajax_loader_2.gif" alt="" style="margin-right:15px;" />',imgLoader='<img src="'+config.extensionUrl+'images/ajax_loader.gif" alt="" style="margin-right:15px;" />';
(function(a){shoutbox.onProgress=function(b){b.lengthComputable&&(shoutbox.iH("msg_txt","Progress: "+b.loaded/b.total*100+"%",!1),setTimeout(shoutbox.iH("msg_txt","",!1),500))};shoutbox.handle=function(b){switch(b.name){case "E_USER_ERROR":case "E_CORE_ERROR":shoutbox.message(b.message,!0,!1,!1);break;default:var c=bzhLang.JS_ERR;c+=b.message;b.lineNumber&&(c+="\n"+bzhLang.LINE+": "+b.lineNumber);b.fileName&&(c+="\n"+bzhLang.FILE+" : "+b.fileName);shoutbox.message(c,!0,!1,!1)}shoutbox.playSound(2,
!0);clearInterval(timerIn)};shoutbox.shoutInsertText=function(b,c){var d=document.forms.postform.elements.chat_message;c&&(b=" "+b+" ");if(isNaN(d.selectionStart)||is_ie)d.createTextRange&&d.caretPos?(baseHeight!=d.caretPos.boundingHeight&&(d.focus(),storeCaret(d)),d=d.caretPos,d.text=" "==d.text.charAt(d.text.length-1)?d.text+b+" ":d.text+b):d.value+=b;else{var e=d.selectionStart,g=d.selectionEnd;mozWrap(d,b,"");d.selectionStart=e+b.length;d.selectionEnd=g+b.length}};shoutbox.shoutPopup=function(b,
c,d,e){e=""==e?"_popup":e;window.open(b.replace(/&amp;/g,"&"),e,"width="+c+",height="+d+",resizable=yes,toolbar=0,menubar=0,scrollbars=yes,statusbar=0,copyhistory=0,top=0,left=0");return!1};shoutbox.passwordSwitch=function(){a("#passwordTxtShout").is(":visible")?(a("#assist-icon-shout").removeClass("shout-icon-assist-show").addClass("shout-icon-assist-hide"),a("#passwordTxtShout").hide().prop("aria-hidden",!0).off("input").off("input focus").off("blur"),a("#password_shout").removeClass("off-screen").prop("aria-hidden",
!1).off("input",function(){a("#passwordTxtShout").val(a("#password_shout").val())}),a("#assist-msg-shout").text(bzhLang.AFFICHE),a("#assist-btn-shout").attr("title",bzhLang.AFFICHE)):(a("#assist-icon-shout").removeClass("shout-icon-assist-hide").addClass("shout-icon-assist-show"),a("#password_shout").addClass("off-screen").prop("aria-hidden",!0).on("input",function(){a("#passwordTxtShout").val(a("#password_shout").val())}),a("#passwordTxtShout").val(a("#password_shout").val()).show().prop("aria-hidden",
!1).on("input",function(){a("#password_shout").val(a("#passwordTxtShout").val())}),a("#assist-msg-shout").text(bzhLang.CACHE),a("#assist-btn-shout").attr("title",bzhLang.CACHE))};shoutbox.cookieShout=function(b,c,d){var e="";d&&(e=new Date,e.setTime(e.getTime()+864E5*d),e="; expires="+e.toGMTString());document.cookie=config.cookieName+b+"="+shoutbox.encodeUtf8(c)+e+config.cookieDomain+config.cookiePath};shoutbox.getCookie=function(b){b=config.cookieName+b+"=";for(var c=document.cookie.split(";"),
d=0;d<c.length;d++){for(var e=c[d];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(b))return shoutbox.decodeUtf8(e.substring(b.length,e.length))}return!1};shoutbox.eraseCookie=function(b){shoutbox.cookieShout(b,"",-1)};shoutbox.goName=function(){a("#shoutnameyes").html(ajaxLoaderOn).show();var b=a("#shoutname").val();b.length<config.minName||b.length>config.maxName?setTimeout(shoutbox.goNameRed,1500):(shoutbox.cookieShout("shout-name",b,60),setTimeout(shoutbox.goNameGreen,1500))};shoutbox.goNameRed=
function(){a("#shoutnameyes").html(bzhLang.USERNAME_EXPLAIN).css({color:"red","font-weight":"bold"})};shoutbox.goNameGreen=function(){a("#shoutnameyes").html(bzhLang.CHOICE_YES).css({color:"green","font-weight":"normal"})};shoutbox.createInput=function(b){var c=shoutbox.cE("input","chat_message",b?"shout-text-user":"inputbox","margin-"+config.direction+":6px;color:#9a9a9a;border-radius:3px;max-width:41%;width:"+config.widthPost+"px;",!1,!1,!1,!1,"chat_message");c.value=bzhLang.AUTO;c.spellcheck=!0;
c.onclick=function(){shoutbox.suppText()};c.onfocus=function(){shoutbox.suppText()};c.onblur=function(){shoutbox.addText()};c.onkeypress=!1===b?function(d){return 13===d.keyCode?(a("#postUser").click(),this.returnValue=d.returnValue=!1):!0}:function(d){return 13===d.keyCode?(a("#postAction").click(),this.returnValue=d.returnValue=!1):!0};return c};shoutbox.setRobot=function(){var b=shoutbox.getCookie("shout-robot"),c="1"==b?"0":"1",d="1"==b?"on":"off";b="1"==b?"off":"on";shoutbox.cookieShout("shout-robot",
c,60);shoutbox.playSound(6,!0);a("#onBot").val(c);a("#iconBot").removeClass("button_shout_bot_"+d).addClass("button_shout_bot_"+b).attr("title",bzhLang["ROBOT_"+b.toUpperCase()]);onCount=0;clearInterval(timerIn);shoutbox.loadMessages()};shoutbox.permutUser=function(b){var c=shoutbox.createInput(b);a("#chat_message").remove();a("#span-post").remove();b?(b=shoutbox.cE("span","span-post",!1,"margin-"+config.direction+":6px;max-width:45%;display:inline-block;width:"+config.widthPost+"px;",!1,!1,!1,!1,
!1),a(c).insertBefore("#postAction"),a(b).insertBefore("#postUser")):a(c).insertBefore("#postUser")};shoutbox.message=function(b,c,d,e){var g=c?"red":"green";c=c?5E3:3E3;var f="center";if("object"===typeof b){var h='<span style="color:black;font-weight:bold;">'+bzhLang.ERROR+" : </span>";h+=b.message?b.message:"";h+=b.line?'<br /><span style="color:black;font-weight:bold;">'+bzhLang.LINE+" : </span>"+b.line:"";h+=b.file?'<br /><span style="color:black;font-weight:bold;">'+bzhLang.FILE+" : </span>"+
b.file:"";h+=b.content?'<br /><span style="color:black;font-weight:bold;">'+bzhLang.POST_DETAILS+" : </span>"+b.content:"";h+=b.MESSAGE_TITLE?b.MESSAGE_TITLE:"";h+=b.MESSAGE_TEXT?"<br />"+b.MESSAGE_TEXT:"";f=config.direction;!1===b.S_USER_NOTICE&&!1===b.S_USER_WARNING||clearInterval(timerIn)}else h=b;a("#msg_txt").length?a("#msg_txt").html('<p id="msg_p"></p>').addClass("message-text").show():a("#shoutbox").html('<ul id="msg_txt" class="topiclist forums" style="height:40px;"><li id="msg_li" style="display:block;"><dl id="msg_dl" style="width:100%;"><dt id="msg_dt" class="row"><p id="msg_p" class="message-text"></p></dt></dl></li></ul>');
a("#msg_p").html(h).css({margin:"0.5em","text-align":f,color:g});d&&(1<d?setTimeout(shoutbox.clearAfter,d):setTimeout(shoutbox.clearAfter,c));e&&shoutbox.reloadAll(!1,!0);a("#post_message").show()};shoutbox.reloadAll=function(b,c){clearInterval(timerIn);c&&(onCount=0);b?timerIn=setInterval(shoutbox.checkMessage,config.requestOn):(a("#openEdit").val(0),a("#nBErrors").val(0),shoutbox.setQuery(),shoutbox.loadMessages())};shoutbox.setError=function(b){b++;a("#nBErrors").val(b);6<b&&shoutbox.reloadAll(!0,
!1)};shoutbox.clearAfter=function(){a("#msg_txt").html("").removeClass("message-text").hide();a("#chat_message").css("background","")};shoutbox.cp=function(){return shoutbox.cE("span",!1,"page-sep",!1,!1,!1,bzhLang.COMMA_SEPARATOR,!1,!1,!1)};shoutbox.cE=function(b,c,d,e,g,f,h,q,k){b=document.createElement(b);c&&(b.id=c);d&&(b.className=d);e&&(b.style.cssText=e);if(g||""===g)b.title=g;f&&(b.type=f);h&&(b.innerHTML=h);q&&(b.alt=q);k?b.name=k:c&&(b.name=c);return b};shoutbox.cTN=function(b){return document.createTextNode(b)};
shoutbox.iH=function(b,c,d){a("#"+b).length&&(!1!==d&&shoutbox.sE(b,d),a("#"+b).html(c))};shoutbox.sE=function(b,c){if(a("#"+b).length)switch(c){case 1:a("#"+b).show();break;case 2:a("#"+b).hide();break;case 3:a("#"+b).css("display","inline");break;case 4:a("#"+b).css("display","inline-block")}};shoutbox.setQuery=function(){$queryNb=0;a("#nBQuery").val($queryNb)};shoutbox.trim=function(b){return b=b.replace(/^\s+/,"").replace(/\s+$/,"")};shoutbox.encodeUtf8=function(b){return encodeURIComponent(b)};
shoutbox.decodeUtf8=function(b){return decodeURIComponent(b)};shoutbox.htmlEncode=function(b){return a("<div/>").text(b).html()};shoutbox.htmlDecode=function(b){return a("<div/>").html(b).text()};shoutbox.playSound=function(b,c){var d=!1;c?d=!0:config.isGuest?"1"==shoutbox.getCookie("shout-sound")&&(d=!0):1==a("#onSound").val()&&(d=!0);!1!==d&&"off"!==a("#shoutAudio-"+b).attr("title")&&(a("#shoutAudio-"+b).prop("paused")?a("#shoutAudio-"+b).trigger("play"):a("#shoutAudio-"+b).trigger("pause"))};shoutbox.replaceAll=
function(b,c,d){return b.replace(new RegExp(c,"g"),d)};shoutbox.infoCookies=function(){a("#questionCookies").attr({onclick:"shoutbox.closeCookies();",title:bzhLang.DIV_CLOSE});a("#i-question").removeClass("fa-question").addClass("fa-question-circle");a.ajax({type:"POST",dataType:"json",url:config.questionUrl,data:dataRun,cache:!1,success:function(b){setTimeout(shoutbox.closeCookies,2E4);var c=config.barHaute?"message-text":"message-text-bottom";var d="<h3>"+b.title+"</h3>";d+='<div class="shout-bold" style="margin:8px;text-align:left;">'+
b.info+" :</div>";d=d+'<div style="margin:0 0 5px 12px;text-align:left;"><ul><li>1. <span class="shout-bold">shout-robot</span> : '+(b.robot+"</li>");d+='<li>2. <span class="shout-bold">shout-sound</span> : '+b.sound+"</li>";d+=""!==b.name?'<li>3. <span class="shout-bold">shout-name</span> : '+b.name+"</li>":"";d+="</ul></div>";a("#msg_txt").html(d).addClass(c).show()},error:function(){a("#questionCookies").attr({onclick:"shoutbox.infoCookies();",title:bzhLang.COOKIES});a("#i-question").removeClass("fa-question-circle").addClass("fa-question")}})};
shoutbox.closeCookies=function(){clearTimeout(timerCookies);if(a("#msg_txt").is(":visible")){var b=config.barHaute?"message-text":"message-text-bottom";a("#msg_txt").html("").removeClass(b).hide();a("#questionCookies").attr({onclick:"shoutbox.infoCookies();",title:bzhLang.COOKIES});a("#i-question").removeClass("fa-question-circle").addClass("fa-question")}};shoutbox.shoutRules=function(){a("#shout_rules").is(":visible")||a("#shout_rules").show();a("#rules_on").html('<div style="text-align:center;">'+
imgLoader+"</div>");a.ajax({type:"POST",dataType:"json",url:config.rulesUrl,data:dataRun,cache:!1,headers:headersContent,success:function(b){1==b.sort?a("#rules_on").html(b.texte):a("#rules_on").html("")},error:function(){a("#shout_rules").hide();a("#rules_on").html("")}})};shoutbox.changePerso=function(b){a("#user_action").hide();a("#shout_bbcode").show();a("#button_shout_text").attr("title",bzhLang.DIV_BBCODE_CLOSE);shoutbox.iH("shoutcheck",ajaxLoaderOn,!1);a.ajax({type:"POST",dataType:"json",url:config.persoUrl,
data:dataRun+"&other="+b,cache:!1,headers:headersContent,success:function(c){shoutbox.iH("shoutcheck","",!1);c.error?shoutbox.message(c,!0,5E3,!0):(c.id!==config.userId?(c.name=bzhLang.ACTION_CITE_ON+": "+c.name,a("#user_inp_bbcode").val(c.id)):a("#user_inp_bbcode").val(0),a("#h3userbbcode").html(c.name),a("#shout_text1").val(c.before),a("#shout_text2").val(c.after),a("#shoutexemple").html(c.message))},error:function(){a("#shout_bbcode").hide()}})};shoutbox.closePersoBbcode=function(){a("#shout_bbcode").hide();
a("#user_inp_bbcode").val("");a("#h3userbbcode").html("");a("#shout_text1").val("");a("#shout_text2").val("");a("#shoutexemple").html("");a("#button_shout_text").attr("title",bzhLang.PERSO)};shoutbox.deleteMessage=function(b){a.ajax({type:"POST",dataType:"json",url:config.deleteUrl,data:dataRun+"&post="+b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):1===c.type?(shoutbox.playSound(3,!1),shoutbox.message(bzhLang.MSG_DEL_DONE,!1,800,!0)):1<c.type&&shoutbox.message(c.message,
!0,2E3,!0)},error:function(){shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.purgeShout=function(b,c){shoutbox.message(bzhLang.PURGE_PROCESS,!1,1,!1);a.ajax({type:"POST",dataType:"json",url:c?config.purgeBotUrl:config.purgeUrl,data:dataRun+"&purge_sort="+b,cache:!1,headers:headersContent,success:function(d){d.error?shoutbox.message(d,!0,5E3,!0):1===d.type?(shoutbox.setQuery(),shoutbox.playSound(3,!1),shoutbox.message(bzhLang.PURGE_PROCESS+" - "+bzhLang.ACTION_CITE_ON+" "+d.nr+" "+(1<d.nr?
bzhLang.MESSAGES:bzhLang.MESSAGE),!1,1,!1),a("#"+id).removeAttr("style"),a("#shoutLast").val(0)):2===d.type&&shoutbox.message(d.message,!0,2E3,!0)},error:function(){shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.suppText=function(){if(a("#chat_message").val()==bzhLang.AUTO)a("#chat_message").val("");else{var b=a("#chat_message").val();b=b.replace(bzhLang.AUTO,"");a("#chat_message").val(b)}a("#chat_message").css("color","black")};shoutbox.addText=function(){if(""==a("#chat_message").val())a("#chat_message").val(bzhLang.AUTO);
else if(a("#chat_message").val()!=bzhLang.AUTO){var b=a("#chat_message").val().replace(bzhLang.AUTO,"");a("#chat_message").val(b)}a("#chat_message").val()==bzhLang.AUTO?a("#chat_message").css("color","#9A9A9A"):a("#chat_message").css("color","black")};shoutbox.closeAction=function(){a("#span-post").length&&shoutbox.permutUser(!1);shoutbox.iH("h3user","",!1);shoutbox.iH("shout_url","",!1);shoutbox.iH("shout_avatar","",!1);shoutbox.sE("user_action",2);a("#user_cite").val("");a("#user_inp").val("");
a("#user_inp_sort").val("")};shoutbox.closeAll=function(){a("#colour_shoutbox").length&&a("#colour_shoutbox").is(":visible")&&(shoutbox.sE("colour_shoutbox",2),a("#color_shout1").attr("title",bzhLang.COLOR));a("#shout_chars").length&&a("#shout_chars").is(":visible")&&(shoutbox.sE("shout_chars",2),a("#chars01").attr("title",bzhLang.CHARS));a("#shoutbox_posting").length&&a("#shoutbox_posting").is(":visible")&&(shoutbox.sE("shoutbox_posting",2),a("#bbcodebutton").attr("title",bzhLang.BBCODES));a("#shout_bbcode").length&&
a("#shout_bbcode").is(":visible")&&(shoutbox.sE("shout_bbcode",2),a("#button_shout_text").attr("title",bzhLang.PERSO))};shoutbox.onTime=function(){$queryNb++;a("#nBQuery").val($queryNb);var b=config.requestOn/1E3*$queryNb,c=Math.floor(b/3600),d=Math.floor(b/60-60*c);b=b-60*d-3600*c;c=(c?10>c?"0"+c+":":c+":":"")+(10>d?"0"+d:d)+":"+(10>b?"0"+b:b);a("#nBTemps").val(c);a("#tempSpan").html(c)};shoutbox.shoutReq=function(b,c,d){""==a("#shout_text1").val()&&""==a("#shout_text2").val()&&(b=c=1);a("#shoutcheck").html(ajaxLoaderOn);
a.ajax({type:"POST",dataType:"json",url:config.ubbcodeUrl,data:dataRun+"&open="+shoutbox.encodeUtf8(b)+"&close="+shoutbox.encodeUtf8(c)+"&other="+d,cache:!1,headers:headersContent,success:function(e){a("#shoutcheck").html('<span id="shoutCheckSpan"></span>');if(e.error)shoutbox.message(e,!0,5E3,!0);else{var g="green";switch(e.type){case 1:a("#shout_text1").val("");a("#shout_text2").val("");a("#shoutexemple").html(e.text);break;case 2:g="red";break;case 3:a("#shout_text1").html(e.before);a("#shout_text2").html(e.after);
a("#shoutexemple").html(e.text);break;case 4:g="blue";a("#shoutexemple").html(e.text);break;case 5:g="red"}a("#shoutCheckSpan").html(e.message).css("color",g)}},error:function(){a("#shoutcheck").html("");shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.shoutOnline=function(){a("#online_shout").html(imgChargeOn).css("text-align","center");a.ajax({type:"POST",dataType:"json",url:config.onlineUrl,data:dataRun,cache:!1,headers:headersContent,success:function(b){a("#online_shout").html('<div id="online_shout1"></div><hr /><div id="online_shout2"></div>').css("text-align",
config.direction);a("#online_shout1").html(b.title);a("#online_shout2").html(b.list)},error:function(){clearTimeout(timerOnline);shoutbox.shoutOnline();timerOnline=setInterval(shoutbox.shoutOnline,3E4)}})};shoutbox.actionUser=function(b){isNaN(b)?shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1):(a("#user_shout").show(),a("#user_action").show(),a("#shout_url").attr("style","").show(),shoutbox.sE("msg_user_shout",2),shoutbox.iH("shout_url",imgChargeOn,!1),a("#user_cite").val(""),a("#user_inp").val(""),
a("#shout_avatar").html(""),a.ajax({type:"POST",dataType:"json",url:config.actUrl,data:dataRun+"&other="+b,cache:!1,headers:headersContent,success:function(c){if(c.error)shoutbox.message(c,!0,5E3,!0);else if(1===c.t)shoutbox.message(c,!0,1,!1),shoutbox.sE("user_action",2);else if(0===c.type)shoutbox.closeAction(),shoutbox.message(c.message,!0,3E3,!1);else if(1===c.type)shoutbox.closeAction();else if(2===c.type)a("#h3user").html(c.username),a("#shout_url").html(c.message).css("color","red");else if(3===
c.type){tpl={open:'<strong>&#187;</strong><span class="profile-shout">',close:"</span></a></span>",span:'<span title="">',"return":"<br /><br />",a:"<a onmouseover=\"shoutbox.iH('onText',this.title,false);\" onmouseout=\"shoutbox.iH('onText','',false);\" class=\"tooltip pointer\"",ext:' onclick="window.open(this.href);return false;" href="'};a("#user_inp").val(c.id);a("#user_inp_sort").val(c.sort);a("#h3user").html(c.username);a("#shout_avatar").html('<span class="avatar-shout">'+c.avatar+"</span>");
var d="<br />"+(c.foe?'<strong>&#187;</strong><span class="profile-shout" style="color:red;">'+bzhLang.USER_IGNORE+tpl.close+tpl["return"]:"");d+=!c.foe&&c.inp?tpl.open+tpl.a+c.url_message+tpl.close+tpl["return"]:"";d+=tpl.open+tpl.a+tpl.ext+c.url_profile+tpl.close+tpl.open+tpl.a+c.url_cite_m+tpl.close+tpl.open+tpl.a+c.url_cite+tpl.close;d+=c.retour?tpl["return"]:"";d+=c.url_admin?tpl.open+tpl.a+tpl.ext+c.url_admin+tpl.close:"";d+=c.url_modo?tpl.open+tpl.a+tpl.ext+c.url_modo+tpl.close:"";d+=c.url_ban?
tpl.open+tpl.a+tpl.ext+c.url_ban+tpl.close:"";d+=c.url_remove?tpl["return"]+tpl.open+tpl.a+c.url_remove+tpl.close:"";d+=c.url_perso?tpl["return"]+tpl.open+tpl.a+c.url_perso+tpl.close:"";d+=c.url_auth?tpl["return"]+tpl.open+tpl.a+c.url_auth+tpl.close:"";d+=c.url_prefs?tpl.open+tpl.a+c.url_prefs+tpl.close:"";d=d+'<br /><hr class="dotted" /><hr class="dotted" />'+(c.inp?tpl.open+tpl.a+c.url_del_to+tpl.close+tpl["return"]:"");d+=c.inp?tpl.open+tpl.a+c.url_del+tpl.close:"";d+=c.url_robot?tpl["return"]+
tpl.open+tpl.a+c.url_robot+tpl.close:"";a("#shout_url").html(d)}},error:function(){shoutbox.sE("user_action",2);shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}}))};shoutbox.runAuth=function(b,c){a.ajax({type:"POST",dataType:"json",url:config.authUrl,data:dataRun+"&other="+b+"&name="+c,cache:!1,headers:headersContent,success:function(d){var e=a("#shout_avatar").html();a("#shout_avatar").html(e+'<h3 class="auth">'+d.username+"</h3>");e='<ul class="ul-auth">';for(var g=0;g<d.nb;g++)e+=""!==d.title[g]?
'<br /><li class="auth-bold">'+d.title[g]+"</li>":"",e+='<li class="li-auth">'+d.data[g]+"</li>";e+="</ul>";a("#shout_url").html(e)}})};shoutbox.sendUserAction=function(){if(""==a("#chat_message").val()||a("#chat_message").val()==bzhLang.AUTO)alert(bzhLang.MESSAGE_EMPTY);else{a("#msg_txt").html(bzhLang.SENDING);var b=dataRun+"&other="+a("#user_inp").val()+"&message="+shoutbox.encodeUtf8(a("#chat_message").val());shoutbox.permutUser(!1);shoutbox.sE("msg_user_shout",2);shoutbox.sE("user_action",2);
shoutbox.iH("shout_url",imgChargeOn,1);shoutbox.closeAll();a.ajax({type:"POST",dataType:"json",url:config.actPostUrl,data:b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):1==c.t?(shoutbox.message(c,!0,"",!0),shoutbox.permutUser(!1)):(a("#chat_message").val(""),a("#user_inp").val(""),a("#user_inp_sort").val(""),1==c.type?(onCount=0,shoutbox.playSound(4,!1),shoutbox.message(bzhLang.POSTED,!1,800,!0),shoutbox.setQuery(),shoutbox.closeAction()):2==c.type?shoutbox.message(c.message,
!0,3E3,!0):(shoutbox.permutUser(!1),a("#msg_txt").html("").hide()))},error:function(){shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})}};shoutbox.removeMsg=function(b){shoutbox.iH("shout_url",imgChargeOn,!1);a.ajax({type:"POST",dataType:"json",url:config.actRemoveUrl,data:dataRun+"&other="+b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):1===c.type?(shoutbox.setQuery(),shoutbox.iH("shout_url",c.message,!1)):shoutbox.sE("formuser",2)},error:function(){shoutbox.iH("shout_url",
"",1);shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.delReqTo=function(b){shoutbox.iH("shout_url",imgChargeOn,!1);a.ajax({type:"POST",dataType:"json",url:config.actDelToUrl,data:dataRun+"&other="+b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):(shoutbox.playSound(3,!1),shoutbox.closeAction(),shoutbox.message(c.message,!1,1,!0))},error:function(){shoutbox.closeAction();shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.delReq=function(b){shoutbox.iH("shout_url",
imgChargeOn,!1);a.ajax({type:"POST",dataType:"json",url:config.actDelUrl,data:dataRun+"&other="+b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):(shoutbox.playSound(3,!1),shoutbox.closeAction(),shoutbox.message(c.message,!1,1,!0))},error:function(){shoutbox.closeAction();shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.citeMsg=function(){onCount=0;a.ajax({type:"POST",dataType:"json",url:config.citeUrl,data:dataRun+"&other="+a("#user_inp").val(),
cache:!1,headers:headersContent,success:function(b){b.error?shoutbox.message(b,!0,5E3,!0):0===b.type?shoutbox.message(b.message,!0,1,!1):1===b.type&&(shoutbox.setQuery(),shoutbox.closeAction(),a("#user_cite").val(b.id),a("#chat_message").focus())},error:function(){shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.citeMultiMsg=function(b,c,d){""!==c?shoutbox.shoutInsertText("[b][color=#"+c+"]"+b+"[/color][/b]",!0):shoutbox.shoutInsertText("[b]"+b+"[/b]",!0);d&&shoutbox.closeAction()};shoutbox.personalMsg=
function(){onCount=0;shoutbox.permutUser(!0);a("#msg_user_shout").show();a("#user_cite").val("");a("#shout_url").html("");a("#shoutMsg").html("&nbsp;&nbsp;"+bzhLang.ACTION_MSG+":");a("#chat_message").focus()};shoutbox.robotMsg=function(b){onCount=0;shoutbox.permutUser(!0);a("#msg_user_shout").show();shoutbox.sE("user_shout",2);shoutbox.iH("shoutMsg","&nbsp;&nbsp;"+bzhLang.MSG_ROBOT+":",!1);shoutbox.iH("h3user","",!1);shoutbox.iH("shout_avatar","");a("#user_inp").val(1);a("#user_inp_sort").val(b);
a("#chat_message").focus()};shoutbox.soundReq=function(){shoutbox.playSound(6,!0);if(config.isGuest){if("1"==shoutbox.getCookie("shout-sound"))var b="0",c=0,d="button_shout_sound_off",e="button_shout_sound",g=bzhLang.CLICK_SOUND_ON;else b="1",c=1,d="button_shout_sound",e="button_shout_sound_off",g=bzhLang.CLICK_SOUND_OFF;shoutbox.cookieShout("shout-sound",b,60);a("#onSound").val(c);a("#iconSound").removeClass(e).addClass(d).attr("title",g)}else a.ajax({type:"POST",dataType:"json",url:config.soundUrl,
data:dataRun+"&sound="+a("#onSound").val(),cache:!1,headers:headersContent,success:function(f){f.error?shoutbox.message(f,!0,5E3,!0):(shoutbox.cookieShout("shout-sound",f.type,60),a("#onSound").val(f.type),a("#iconSound").removeClass(f.classOut).addClass(f.classIn).attr("title",f.title))},error:function(){shoutbox.message(bzhLang.SERVER_ERR,!0,1,!1)}})};shoutbox.runSmileys=function(b,c){a("#smilies").html('<div style="text-align:center;margin:25px auto;">'+imgLoadOn+bzhLang.LOADING+"</div>").show();
a.ajax({type:"POST",dataType:"json",url:b?config.smilUrl:config.smilPopUrl,data:dataRun+"&cat="+c,success:function(d){if(d.error)shoutbox.message(d,!0,5E3,!0),shoutbox.sE("smilies_ul",2),a("#smilies").html("").hide(),a("#iconSmilies").attr("title",bzhLang.SMILIES);else{var e="";"undefined"!==typeof d.title&&d.title&&(e+='<h3 style="margin-top:2px;">'+d.title+"</h3>");"undefined"!==typeof d.emptyRow&&""!==d.emptyRow&&(e+='<span class="pagin_red">'+d.emptyRow+"</span>");for(var g=0;g<d.total;g++){var f=
d.smilies[g];e+='<a class="pointer" onclick="shoutbox.shoutInsertText(\''+f.code+'\',true);return false;" title="'+f.emotion+'">';e+='<img class="smilies" src="'+d.url+f.image+'" alt="'+f.code+'" title="'+f.emotion+'" width="'+f.width+'" height="'+f.height+'"></a> '}e+='<div class="more-smiley"> ... ';0<d.nb_pop&&b?e+='<a class="pointer tooltip" onclick="shoutbox.runSmileys(false,-1);" style="margin:5px;" title="'+bzhLang.MORE_SMILIES_ALT+'"><span title="">'+bzhLang.MORE_SMILIES+"</span></a> ... ":
b||(e+='<a class="pointer tooltip" onclick="shoutbox.runSmileys(true,-1);" style="margin:5px;" title="'+bzhLang.LESS_SMILIES_ALT+'"><span title="">'+bzhLang.LESS_SMILIES+"</span></a> ... ");config.creator&&(e+='<a class="pointer tooltip" onclick="shoutbox.shoutPopup(config.creatorUrl,\'550\',\'570\',\'_phpbbsmiliescreate\');shoutbox.suppText();" style="margin: 5px;" title="'+bzhLang.CREATOR+'"><span title="">'+bzhLang.CREATOR+"</span></a> ... ");if(config.category&&"undefined"!==typeof d.categories)for(e+=
"undefined"!==d.title_cat?'<h3 style="margin-top:8px;">'+d.title_cat+"</h3>":"",g=0;g<d.categories.length;g++){f=d.categories[g];var h=d.cat==f.cat_id?" pagin_red":"";e+=0!==g?" - ":"";e+='<a class="pointer tooltip'+h+'" onclick="shoutbox.runSmileys(false,'+f.cat_id+');" style="margin:5px;" title="'+f.cat_name+'"><span title="">'+f.cat_name+"</span></a>("+f.cat_nb+")"}e+="</div>";a("#smilies").html(e)}},error:function(){shoutbox.sE("smilies_ul",2);a("#smilies").html("").hide();a("#iconSmilies").attr("title",
bzhLang.SMILIES)}})};shoutbox.changePage=function(b){shoutbox.setQuery();onCount=b;a("#shout_messages").fadeOut(600,"linear").fadeIn(600,"linear");a("#msg_txt").hide();shoutbox.reloadAll(!1,!1)};shoutbox.openEdit=function(b){1==a("#openEdit").val()?(shoutbox.playSound(2,!0),alert(bzhLang.ONLY_ONE_OPEN)):(clearInterval(timerIn),a("#openEdit").val(1),a("#post_message").show(),a("#form"+b).css("padding","0 0 5px 5px").show(),shoutbox.sE("shout"+b,2),shoutbox.sE("editButton"+b,2),shoutbox.sE("infoButton"+
b,2),shoutbox.sE("deleteButton"+b,2),shoutbox.sE("dtshout"+b,2),shoutbox.sE("ddshout"+b,2),a("#spa"+b).css("border","0px none").html(bzhLang.EDIT+": "),a("#input"+b).focus())};shoutbox.cancelMessage=function(b){a("#openEdit").val(0);a("#post_message").show();shoutbox.iH("spa"+b,"",!1);shoutbox.sE("form"+b,2);shoutbox.sE("shout"+b,3);shoutbox.sE("editButton"+b,3);shoutbox.sE("dtshout"+b,3);shoutbox.sE("ddshout"+b,3);shoutbox.sE("infoButton"+b,3);shoutbox.sE("deleteButton"+b,3);shoutbox.closeAll();
shoutbox.reloadAll(!0,!1)};shoutbox.editMessage=function(b,c){shoutbox.sE("dtshout"+b,2);shoutbox.sE("ddshout"+b,2);shoutbox.sE("form"+b,2);shoutbox.iH("text"+b,bzhLang.SENDING_EDIT,1);shoutbox.closeAll();var d=dataRun+"&shout_id="+c+"&message="+shoutbox.encodeUtf8(a("#input"+b).val());a.ajax({type:"POST",dataType:"json",url:config.editUrl,data:d,cache:!1,headers:headersContent,success:function(e){e.error?shoutbox.message(e,!0,5E3,!0):(1===e.type?shoutbox.message(e.message,!0,2E3,!0):2===e.type&&
(shoutbox.playSound(5,!1),a("#shout"+e.shout_id).html(e.texte),shoutbox.message(e.message,!1,800,!0)),a("#openEdit").val(0),shoutbox.setQuery(),shoutbox.sE("msgbody"+e.shout_id,2),shoutbox.sE("shout"+e.shout_id,2),shoutbox.sE("editButton"+e.shout_id,3),shoutbox.sE("infoButton"+e.shout_id,3),shoutbox.sE("deleteButton"+e.shout_id,3),a("#post_message").show())}})};shoutbox.sendMessage=function(){if(a("#chat_message").val()==bzhLang.AUTO||""==a("#chat_message").val())shoutbox.message(bzhLang.MESSAGE_EMPTY,
!0,5E3,!0);else if(!config.limitPost&&0<config.maxPost&&a("#chat_message").val().length>config.maxPost)shoutbox.message(bzhLang.TOO_BIG+a("#chat_message").val().length+"<br />"+bzhLang.TOO_BIG2+config.maxPost,!0,5E3,!0);else{var b=dataRun+"&message="+shoutbox.encodeUtf8(a("#chat_message").val());b+=""!==a("#user_cite").val()?"&cite="+a("#user_cite").val():"&cite=0";if(config.isGuest){if(""==a("#shoutname").val()){a("#shout_name").show();shoutbox.message(bzhLang.CHOICE_NAME_ERROR,!0,7E3,!0);return}b+=
"&name="+shoutbox.encodeUtf8(a("#shoutname").val())}shoutbox.setQuery();shoutbox.closeAll();shoutbox.iH("msg_txt","",!1);a("#msg_txt").html(bzhLang.SENDING);a("#chat_message").css("background",'white url("'+config.extensionUrl+'images/ajax_loader.gif") no-repeat 90% 50%');a.ajax({type:"POST",dataType:"json",url:config.postUrl,data:b,cache:!1,headers:headersContent,success:function(c){c.error?shoutbox.message(c,!0,5E3,!0):(1==c.type?(shoutbox.message(c.message,!1,800,!0),shoutbox.playSound(4,!1),a("#post_message").show(),
a("#user_cite").val("").attr("disabled"),a("#user_inp").val(""),a("#chat_message").val("")):2==c.type?shoutbox.message(c.message,!0,2E3,!0):10==c.type?(shoutbox.message(c.message,!0,1,!0),shoutbox.playSound(2,!1),a("#post_message").show(),a("#user_cite").val("").attr("disabled"),a("#user_inp").val(""),a("#chat_message").val("")):shoutbox.reloadAll(!0,!0),onCount=0,a("#chat_message").focus())}})}};shoutbox.setTimezone=function(b){var c=new Date(1E3*b);b=c.getUTCHours();c=c.getMinutes();var d="",e=
config.userTimezone.substring(0,1),g=Number(config.userTimezone.substring(1,3)),f=Number(config.userTimezone.substring(4,6));b="+"==e?b+g:b-g;c+=f;59<c&&(c-=60,b+=1);-1!=config.dateFormat.indexOf("a")?(d=11<b?" pm":" am",b=12<b?b-12:b):b=10>b?"0"+b:b;return b+":"+(10>c?"0"+c:c)+d};shoutbox.refreshTime=function(){var b=Math.floor((new Date).getTime()/1E3),c;a("#shout_messages span[name='time-shout']").each(function(){var d=a(this).attr("time");if(d>b-23700){var e=Math.floor((b-d)/60);1>e?c=bzhLang.DATETIME_0:
1==e?c=bzhLang.DATETIME_1.replace("%d",e):1<e&&60>e?c=bzhLang.DATETIME_2.replace("%d",e):60<=e&&(c=bzhLang.DATETIME_3+(-1!=config.dateFormat.indexOf(",")?", ":" ")+shoutbox.setTimezone(d));a(this).html(c)}})};shoutbox.checkMessage=function(){if(1==a("#openEdit").val())clearInterval(timerIn);else if(3!==config.sortShoutNb||config.privOk)if(shoutbox.onTime(),0!==config.inactivity&&!config.isPriv&&a("#nBQuery").val()>config.inactivity)shoutbox.message(bzhLang.OUT_TIME,!0,!1,!1),clearInterval(timerIn);
else{config.refresh&&shoutbox.refreshTime();var b=a("#shoutLast").val();a.ajax({type:"POST",dataType:"json",url:config.checkUrl+("?t="+Math.floor(1E6*Math.random())),data:dataRun+"&on_bot="+a("#onBot").val(),cache:!1,headers:headersContent,success:function(c){c.error||c.message?shoutbox.message(c,!0,5E3,!1):c.S_USER_NOTICE||c.S_USER_WARNING?shoutbox.message(c,!0,0,!1):1===c.t?(shoutbox.message(c,!0,4E3,!1),shoutbox.reloadAll(!0,!1)):c.t!==b&&(0!==b&&shoutbox.playSound(1,!1),a("#shoutLast").val(c.t),
shoutbox.reloadAll(!1,!0))},error:function(c,d,e){shoutbox.setError(a("#nBErrors").val())}})}else clearInterval(timerIn)};shoutbox.loadPagination=function(b){var c=Math.ceil(b/config.perPage),d=Math.floor(onCount/config.perPage)+1,e="right"==config.direction?"left":"right";if(2>c||b<config.perPage)a("#divnr").hide();else{a("#divnr").show();a("#linr").html('<span id="shout-pagin" class="shout-pagin"></span><span id="tempSpan" style="float:'+e+";margin-"+e+':5px;opacity:0.2;"></span>').show();b=shoutbox.cE("span",
!1,1===d?"pagin_red":"pointer",!1,bzhLang.PAGE+"1",!1,"1",!1,!1);1!==d&&(b.onclick=function(){shoutbox.changePage(0)},e=shoutbox.cE("span",!1,"pointer",!1,bzhLang.PREVIOUS,!1,bzhLang.PREVIOUS+" ",!1,!1),e.onclick=function(){shoutbox.changePage((d-2)*config.perPage)},a(e).appendTo(a("#shout-pagin")));a(b).appendTo(a("#shout-pagin"));var g=Math.min(Math.max(1,d-4),c-5);b=5<c?Math.max(Math.min(c,d+4),6):c;var f=5<c?g+1:2;e=5<c?b-1:c;a(1<g&&5<c?shoutbox.cTN(" ... "):shoutbox.cp()).appendTo(a("#shout-pagin"));
for(g=f;g<b;g++)f=shoutbox.cE("span",!1,g===d?"pagin_red":"pointer",!1,bzhLang.PAGE+g,!1,g,!1,!1),g!==d&&(f.c=(g-1)*config.perPage,f.onclick=function(){shoutbox.changePage(this.c)}),a(f).appendTo(a("#shout-pagin")),a(g<e?shoutbox.cp():shoutbox.cTN("")).appendTo(a("#shout-pagin"));a(5<c?b<c?shoutbox.cTN(" ... "):shoutbox.cp():shoutbox.cTN("")).appendTo(a("#shout-pagin"));b=shoutbox.cE("span",!1,d===c?"pagin_red":"pointer",!1,bzhLang.PAGE+c,!1,c,!1,!1);e=shoutbox.cE("span",!1,!1,!1,!1,!1,!1,!1,!1);
d!==c&&(b.onclick=function(){shoutbox.changePage((c-1)*config.perPage)},e=shoutbox.cE("span",!1,"pointer",!1,bzhLang.NEXT,!1," "+bzhLang.NEXT,!1,!1),e.onclick=function(){shoutbox.changePage(d*config.perPage)});a(b).appendTo(a("#shout-pagin"));a(e).appendTo(a("#shout-pagin"))}};shoutbox.loadMessages=function(){if(1==a("#openEdit").val())clearInterval(timerIn);else if(3!==config.sortShoutNb||config.privOk)a.ajax({type:"POST",dataType:"json",url:config.viewUrl,data:dataRun+"&start="+onCount+"&l="+a("#shoutLast").val()+
"&on_bot="+a("#onBot").val(),cache:!1,headers:headersContent,success:function(b){if(b.error)shoutbox.message(b,!0,"",!0);else if(1===b.last)shoutbox.message(b,!0,1,!1),shoutbox.iH("shout_messages",!1);else if(a("#shout_messages").html(""),0===b.total)config.postOk&&first&&(a("#post_message").show(),first=!1),a("#shout_messages").append('<div class="shout_centered">'+bzhLang.NO_MESSAGE+"</div>");else{config.isRobot||shoutbox.loadPagination(b.number);a("#shoutLast").val(b.last);var c=Math.floor((new Date).getTime()/
1E3),d=1,e="",g=q=k=!1;e=config.toBottom?b.messages:b.messages.reverse();for(var f=0;f<b.total;f++){var h=e[f];g=h.deletemsg;var q=h.edit,k=h.showIp,v=h.other&&config.postOk&&config.isUser&&config.buttonCite?!0:!1,z=shoutbox.cE("li","lishout"+f,"row row"+d+" bg"+d,!1,!1,!1,!1,!1,!1),w=shoutbox.cE("dl","dlshout"+f,!1,!1,!1,!1,!1,!1,!1);d=1===d?2:1;var n=shoutbox.cE("span","deleteButton"+f,!1,!1,!1,!1,!1,!1,!1),l=shoutbox.cE("span","editButton"+f,!1,!1,!1,!1,!1,!1,!1),t=shoutbox.cE("span","infoButton"+
f,!1,!1,!1,!1,!1,!1,!1),y=shoutbox.cE("span","citeButton"+f,!1,!1,!1,!1,!1,!1,!1);g?(n=shoutbox.cE("input","deleteButton"+f,"button_shout_del button_shout_l",!1,bzhLang.DEL,"button",!1,!1,!1),n.shoutId=h.shoutId,n.onclick=function(){confirm(bzhLang.DEL_SHOUT+" message "+this.shoutId)&&shoutbox.deleteMessage(this.shoutId)}):config.buttonsLeft&&(n=shoutbox.cE("input","deleteButton"+f,"button_shout_del_no button_shout_l",!1,bzhLang.NO_DEL,"button",!1,!1,!1),n.onclick=function(){alert(bzhLang.NO_DEL)});
if(q){l=shoutbox.cE("input","editButton"+f,"button_shout_edit button_shout_l",!1,bzhLang.EDIT,"button",!1,!1,!1);l.i=f;l.onclick=function(){shoutbox.openEdit(this.i)};var A=shoutbox.cE("span","text"+f,"span-text-edit",!1,!1,!1,!1,!1,!1),m=shoutbox.cE("form","form"+f,!1,"display:none;",!1,!1,!1,!1,!1);m.spellcheck=!0;m.onsubmit=function(){return!1};var x=shoutbox.cE("span","spa"+f,!1,!1,!1,!1,!1,!1,!1),r=shoutbox.cE("input","input"+f,"input-text-edit",!1,!1,!1,!1,!1,!1);r.value=shoutbox.htmlDecode(h.msgPlain);
r.i=f;r.onkeypress=function(B){if(13==B.keyCode)return a("#submit"+this.i).click(),this.returnValue=B.returnValue=!1};var p=shoutbox.cE("input","submit"+f,"button btnmain","",bzhLang.EDIT,"button",!1,!1,!1);p.i=f;p.shoutId=h.shoutId;p.value=bzhLang.EDIT_MSG;p.onclick=function(){shoutbox.editMessage(this.i,this.shoutId)};var u=shoutbox.cE("input",!1,"button btnmain",!1,bzhLang.CANCEL,"button",!1,!1,!1);u.i=f;u.value=bzhLang.CANCEL;u.onclick=function(){shoutbox.cancelMessage(this.i)}}else config.buttonsLeft&&
(l=shoutbox.cE("input","editButton"+f,"button_shout_edit_no button_shout_l",!1,bzhLang.NO_EDIT,"button",!1,!1,!1),l.onclick=function(){alert(bzhLang.NO_EDIT)});config.buttonIp&&(k?(t=shoutbox.cE("input","infoButton"+f,"button_shout_ip button_shout_l",!1,bzhLang.IP,"button",!1,!1,!1),t.ip=h.shoutIp,t.onclick=function(){alert(bzhLang.POST_IP+"  "+this.ip)}):config.buttonsLeft&&(t=shoutbox.cE("input","infoButton"+f,"button_shout_ip_no button_shout_l",!1,bzhLang.NO_SHOW_IP_PERM,"button",!1,!1,!1),t.onclick=
function(){alert(bzhLang.NO_SHOW_IP_PERM)}));v&&(y=shoutbox.cE("input","citeButton"+f,"button_shout_cite button_shout_l",!1,bzhLang.ACTION_CITE_M,"button",!1,!1,h.name),y.colour=h.colour?h.colour:"",y.onclick=function(){shoutbox.citeMultiMsg(this.name,this.colour,!1)});g=k||q||g||v||config.buttonsLeft?shoutbox.cE("dt","dtshout"+f,"button_background"+(config.endClassBg?config.buttonBg:"")+" dtshout"+config.direction,!1,!1,!1,!1,!1):shoutbox.cE("dt",!1,!1,"padding:0;display:inline;float:"+config.direction,
!1,!1,!1,!1,!1);g.appendChild(n);g.appendChild(l);g.appendChild(t);g.appendChild(y);w.appendChild(g);n=shoutbox.cE("dd","ddshout"+f,!1,"width:auto",!1,!1,(h.timeMsg>c-3700?'<span name="time-shout" time="'+h.timeMsg+'">'+h.shoutTime+"</span>":'<span name="no-time-shout">'+h.shoutTime+"</span>")+(h.avatar&&1<h.avatar.length?bzhLang.SEP+'<span class="avatar-shout">'+h.avatar+"</span>":"")+bzhLang.SEP+h.username+":",!1,!1);l=shoutbox.cE("dd","msgbody"+f,"msgbody"+config.direction,!1,!1,!1,!1,!1,!1);l.appendChild(shoutbox.cE("span",
"shout"+f,"msg_shout",!1,!1,!1,h.shoutText,!1,!1));q&&(m.appendChild(x),m.appendChild(r),m.appendChild(p),m.appendChild(u),l.appendChild(m),l.appendChild(A));w.appendChild(n);w.appendChild(l);z.appendChild(w);a("#shout_messages").append(z)}config.toBottom?a("#shout_messages").scrollTop(0):a("#shout_messages").scrollTop(a("#shout_messages").prop("scrollHeight"))}},error:function(){clearInterval(timerIn);shoutbox.loadMessages()}}),timerIn=setInterval(shoutbox.checkMessage,config.requestOn)};shoutbox.writeShoutbox=
function(){try{if(3!==config.sortShoutNb||config.privOk){a("#shout-1").html('<i class="icon fa-commenting fa-fw" aria-hidden="false"></i><a href="'+config.titleUrl+'" onclick="window.open(this.href);return false" title="'+bzhLang.TITLE+'">'+bzhLang.TITLE+"</a>").removeClass("shout-left-dt").addClass("shout-"+config.direction+"-dt");a("#shout-2").html(bzhLang.PRINT_VER+'<i class="icon fa-info fa-fw" aria-hidden="false"></i>').removeClass("shout-left-dd").addClass("shout-"+config.direction+"-dd");a("#sortShoutNb").val(config.sortShoutNb);
a("#onSound").val(config.enableSound);config.isGuest&&(!1===shoutbox.getCookie("shout-sound")?shoutbox.cookieShout("shout-sound",config.enableSound,60):a("#onSound").val(shoutbox.getCookie("shout-sound")),!1!==shoutbox.getCookie("shout-name")&&a("#shoutname").val(shoutbox.getCookie("shout-name")));!1===shoutbox.getCookie("shout-robot")?shoutbox.cookieShout("shout-robot","1",60):a("#onBot").val(shoutbox.getCookie("shout-robot"));var b=config.postOk?"":"text-align:center;padding:3px;";b+=config.barHaute?
"":"border-bottom:none;";var c="display:block;padding:3px 0 3px 1px;width:100%;";config.postOk||(c="float:none;width:100%;");var d=shoutbox.cE("ul","base_ul","topiclist forums",!1,!1,!1,!1,!1,!1),e=shoutbox.cE("li","shoutbar","button_background"+config.buttonBg,b,!1,!1,!1,!1,!1),g=shoutbox.cE("dl","shoutdl",!1,"width:100%;",!1,!1,!1,!1,!1),f=shoutbox.cE("dt","post_message",!1,c,!1,!1,!1,!1,!1),h=shoutbox.cE("div","postingBox",!1,"height:auto;width:100%;overflow-wrap:break-word;",!1,!1,!1,!1,!1),q=
shoutbox.cE("span","audioShout","no_display",!1,!1,!1,!1,!1,"audioShout"),k=[[1,"new",config.newSound],[2,"error",config.errorSound],[3,"del",config.delSound],[4,"add",config.addSound],[5,"edit",config.editSound],[6,"auto","discretion"]];for(b=0;b<k.length;b++){var v=shoutbox.cE("audio","shoutAudio-"+k[b][0],!1,!1,k[b][1],"audio/mpeg",!1,!1,"shoutAudio-"+k[b][0]);"1"!==k[b][2]?(v.src=config.extensionUrl+"sounds/"+k[b][2]+".mp3",v.preload="auto"):v.title="off";q.appendChild(v)}var z=1==a("#onSound").val()?
!0:!1,w=shoutbox.cE("input","iconSound","button_shout_sound"+(z?"":"_off")+" button_shout","",z?bzhLang.CLICK_SOUND_OFF:bzhLang.CLICK_SOUND_ON,"button",!1,!1,!1);w.onclick=function(){shoutbox.soundReq()};var n=1==a("#onBot").val()?"on":"off",l=bzhLang["ROBOT_"+n.toUpperCase()],t=shoutbox.cE("input","iconBot","button_shout_bot_"+n+" shout_bot button_shout","",l,"button",!1,!1,!1);t.onclick=function(){shoutbox.setRobot()};if(config.postOk){var y=shoutbox.createInput(!1);h.appendChild(y);var A=shoutbox.cE("input",
"postUser","button btnmain","margin-"+config.direction+":6px;border-radius:4px;line-height:1.3;",bzhLang.POST_MESSAGE_ALT,"button",!1,!1,"postUser");A.value=bzhLang.POST_MESSAGE;A.onclick=function(){shoutbox.sendMessage()};h.appendChild(A);if(config.smiliesOk){var m=shoutbox.cE("input","iconSmilies","button_shout_smile button_shout","margin-"+config.direction+":4px;",bzhLang.SMILIES,"button",!1,!1,"iconSmilies");m.onclick=function(){a("#smilies").is(":visible")?(a("#smilies_ul").hide(),a("#smilies").html("").hide(),
a("#iconSmilies").attr("title",bzhLang.SMILIES),shoutbox.addText()):(a("#iconSmilies").attr("title",bzhLang.SMILIES_CLOSE),a("#smilies_ul").show(),shoutbox.suppText(),shoutbox.runSmileys(!0,-1))};h.appendChild(m)}else config.seeButtons&&(m=shoutbox.cE("input",!1,"button_shout_smile_no button_shout","",bzhLang.NO_SMILIES,"button",!1,!1,!1),m.onclick=function(){alert(bzhLang.NO_SMILIES)},h.appendChild(m));if(config.colorOk){var x=shoutbox.cE("input","color_shout1","button_shout_color button_shout",
"",bzhLang.COLOR,"button",!1,!1,!1);x.onclick=function(){a("#colour_shoutbox").is(":visible")?(a("#colour_shoutbox").hide(),a("#color_shout1").attr("title",bzhLang.COLOR),shoutbox.addText()):(a("#colour_shoutbox").show(),a("#color_shout1").attr("title",bzhLang.COLOR_CLOSE),shoutbox.suppText())};h.appendChild(x)}else config.seeButtons&&(x=shoutbox.cE("input","color_shout1","button_shout_color_no button_shout","",bzhLang.NO_COLOR,"button",!1,!1,!1),x.onclick=function(){alert(bzhLang.NO_COLOR)},h.appendChild(x));
if(config.charsOk){var r=shoutbox.cE("input","chars01","button_shout_chars button_shout","",bzhLang.CHARS,"button",!1,!1,!1);r.onclick=function(){if(a("#shout_chars").is(":visible"))a("#shout_chars").hide(),a("#char_shout1").html(""),a("#chars01").attr("title",bzhLang.CHARS);else{var C=config.isMobile?25:1===config.sortShoutNb?29:38;a("#shout_chars").show();a("#char_shout1").html(shoutbox.specialCharShout(C));shoutbox.mouseChar();a("#chars01").attr("title",bzhLang.CHARS_CLOSE)}};h.appendChild(r)}else config.seeButtons&&
(r=shoutbox.cE("input","chars01","button_shout_chars_no button_shout","",bzhLang.NO_CHARS,"button",!1,!1,!1),r.onclick=function(){alert(bzhLang.NO_CHARS)},h.appendChild(r));if(config.bbcodeOk){var p=shoutbox.cE("input","bbcodebutton","button_shout_img button_shout","",bzhLang.BBCODES,"button",!1,!1,!1);p.onclick=function(){a("#shoutbox_posting").is(":visible")?(a("#shoutbox_posting").hide(),a("#bbcodebutton").attr("title",bzhLang.BBCODES)):(a("#shoutbox_posting").show(),a("#bbcodebutton").attr("title",
bzhLang.BBCODES_CLOSE))};h.appendChild(p)}else config.seeButtons&&(p=shoutbox.cE("input","bbcodebutton","button_shout_img_no button_shout","",bzhLang.NO_BBCODES,"button",!1,!1,!1),p.onclick=function(){alert(bzhLang.NO_BBCODE)},h.appendChild(p));if(1!==config.sortShoutNb){if(config.popupOk){var u=shoutbox.cE("input",!1,"button_shout_popup button_shout","",bzhLang.POP,"button",!1,!1,!1);u.onclick=function(){shoutbox.shoutPopup(config.popupUrl,config.popupWidth,config.popupHeight,"_popup");return!1}}else config.seeButtons&&
(u=shoutbox.cE("input",!1,"button_shout_popup_no button_shout","",bzhLang.NO_POP,"button",!1,!1,!1),u.onclick=function(){alert(bzhLang.NO_POP)});h.appendChild(u);if(config.purgeOn){var B=shoutbox.cE("input","purgeRobot","button_shout_robot button_shout","",bzhLang.PURGE_ROBOT_ALT,"button",!1,!1,!1);B.onclick=function(){confirm(bzhLang.PURGE_ROBOT_BOX)&&shoutbox.purgeShout("purge_robot"+(config.isPriv?"_priv":""),!0)};var D=shoutbox.cE("input","purge","button_shout_purge button_shout","",bzhLang.PURGE_ALT,
"button",!1,!1,!1);D.onclick=function(){confirm(bzhLang.PURGE_BOX)&&shoutbox.purgeShout("purge"+(config.isPriv?"_priv":""),!1)};h.appendChild(B);h.appendChild(D)}}if(config.isUser){if(3!==config.sortShoutNb&&config.privOk){var E=shoutbox.cE("input",!1,"button_shout_priv button_shout","",bzhLang.PRIV,"button",!1,!1,!1);E.onclick=function(){window.open(config.privUrl)};h.appendChild(E)}if(config.formatOk){var F=shoutbox.cE("input","button_shout_text","button_shout_text button_shout","",bzhLang.PERSO,
"button",!1,!1,!1);F.onclick=function(){a("#shout_bbcode").is(":visible")?shoutbox.closePersoBbcode():shoutbox.changePerso(config.userId)};h.appendChild(F)}var G=shoutbox.cE("input",!1,"button_shout_config button_shout","",bzhLang.CONFIG_OPEN,"button",!1,!1,!1);G.onclick=function(){shoutbox.shoutPopup(config.configUrl,"850","500","_popup")};h.appendChild(G)}if(config.rulesOk){var H=config.isPriv?bzhLang.RULES_PRIV:bzhLang.RULES,I=shoutbox.cE("input","buttonRules","button_shout_rules button_shout",
"",config.rulesOpen?bzhLang.RULES_CLOSE:H,"button",!1,!1,!1);I.onclick=function(){a("#shout_rules").is(":visible")?(a("#rules_on").html(""),a("#shout_rules").hide(),a("#buttonRules").attr("title",H)):(shoutbox.shoutRules(),a("#buttonRules").attr("title",bzhLang.RULES_CLOSE))};h.appendChild(I)}if(config.onlineOk){var J=shoutbox.cE("input","buttonOnline","button_shout_online button_shout","",bzhLang.ONLINE,"button",!1,!1,!1);J.onclick=function(){a("#shout_online").is(":visible")?(a("#shout_online").hide(),
a("#buttonOnline").attr("title",bzhLang.ONLINE),clearTimeout(timerOnline)):(a("#shout_online").show(),a("#buttonOnline").attr("title",bzhLang.ONLINE_CLOSE),shoutbox.shoutOnline(),timerOnline=setInterval(shoutbox.shoutOnline,3E4))};h.appendChild(J)}if(config.isGuest){var K=shoutbox.cE("input","iconConnect","button_shout_connect button_shout","",bzhLang.CLICK_HERE,"button",!1,!1,!1);K.onclick=function(){a("#shout_connect").is(":hidden")?(a("#shout_connect").show(),a("#iconConnect").attr({"class":"button_shout_connect_on button_shout",
title:bzhLang.DIV_CLOSE})):(a("#shout_connect").hide(),a("#iconConnect").attr({"class":"button_shout_connect button_shout",title:bzhLang.CLICK_HERE}))};var L=shoutbox.cE("input","iconName","button_shout_name button_shout","",bzhLang.CHOICE_NAME,"button",!1,!1,!1);L.onclick=function(){a("#shout_name").is(":hidden")?(a("#shout_name").show(),a("#iconName").attr({"class":"button_shout_name_on button_shout",title:bzhLang.DIV_CLOSE})):(a("#shout_name").hide(),a("#iconName").attr({"class":"button_shout_name button_shout",
title:bzhLang.CHOICE_NAME}));shoutbox.sE("shoutnameyes",2)};h.appendChild(K);h.appendChild(L)}config.barHaute&&(f.appendChild(h),g.appendChild(f),e.appendChild(g),d.appendChild(e));a("#abbc3_buttons").length&&a("#abbc3_buttons").css("margin","0")}else{var M=config.isGuest?bzhLang.CLICK_HERE:bzhLang.NO_POST_PERM,N=shoutbox.cE("a","printPerm","pointer",!1,M,!1,M,!1,!1);config.isGuest&&(N.onclick=function(){a("#shout_connect").is(":hidden")?(a("#shout_connect").show(),a("#printPerm").attr("title",bzhLang.DIV_CLOSE)):
(a("#shout_connect").hide(),a("#printPerm").attr("title",bzhLang.CLICK_HERE))});f.appendChild(h);g.appendChild(f);e.appendChild(g);d.appendChild(e);h.appendChild(N)}var Q=shoutbox.cE("a","questionCookies","pointer",!1,bzhLang.COOKIES,!1,'<i id="i-question" class="icon fa-question fa-fw"></i><span></span>',!1,!1);h.appendChild(w);h.appendChild(t);h.appendChild(Q);h.appendChild(q);var R=shoutbox.cE("div","msg_txt",!1,"text-align:center;",!1,!1,!1,!1,!1);d.appendChild(R);var S=config.shoutImgHori.replace("right",
"98%"),T=config.shoutImgVert.replace("top","1%"),U=shoutbox.cE("div","shout_messages",!1,"height: "+config.shoutHeight+"px;"+(config.shoutImg?'background: transparent url("'+config.shoutImgUrl+config.shoutImg+'") no-repeat scroll '+S+" "+T+";":""),!1,!1,'<div style="text-align:center;margin:50px auto;">'+imgChargeOn+bzhLang.LOADING+"</div>",!1,!1);d.appendChild(U);!config.barHaute&&config.postOk&&(f.appendChild(h),g.appendChild(f),e.appendChild(g),d.appendChild(e));var O=shoutbox.cE("div","divnr",
!1,!1,!1,!1,!1,!1,!1),P=shoutbox.cE("ul","ulnr","topiclist forums","margin:0;",!1,!1,!1,!1,!1),V=shoutbox.cE("li","linr","pagination button_background"+config.buttonBg,"text-align: "+config.direction+";",!1,!1,!1,!1,!1);P.appendChild(V);O.appendChild(P);d.appendChild(O);a(d).appendTo(a("#shoutbox"));config.rulesOpen&&1!==config.sortShoutNb&&shoutbox.shoutRules();config.barHaute||(a("#shout_rules").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#smilies_ul").css({"border-radius":"0",
"border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#shout_online").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#user_action").length&&a("#user_action").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#colour_shoutbox").length&&a("#colour_shoutbox").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#shout_chars").length&&a("#shout_chars").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),
a("#shoutbox_posting").length&&a("#shoutbox_posting").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#shout_bbcode").length&&a("#shout_bbcode").css({"border-radius":"0","border-top":"1px solid darkgrey"}).insertBefore("#divnr"),a("#msg_txt").insertAfter("#shout_messages"));a("#questionCookies").attr("onclick","shoutbox.infoCookies();");1===config.sortShoutNb&&a(".copyright").hide();a("#format-buttons").length?(a(".format-buttons").css({margin:"0",padding:"10px 0 10px 0",
"text-align":"center"}),a(".format-buttons .button").css({padding:"4px"}),a(".format-buttons select").css({"font-size":"1.1em"}),a(".format-buttons .button .icon").css({"font-size":"16px"})):a("#format-postingbuttons").length&&(a("#format-postingbuttons").css({margin:"0",padding:"10px 0 10px 0","text-align":"center"}),a("#format-postingbuttons .button").css({padding:"4px"}),a(".format-postingbuttons select").css({"font-size":"1.1em"}),a(".format-postingbuttons .button .icon").css({"font-size":"16px"}));
a("#audioShout audio").each(function(){a(this).attr("volume",.4)});shoutbox.loadMessages()}}catch(C){shoutbox.handle(C)}};shoutbox.specialCharShout=function(b){for(var c=[["&euro;","&#8364;","euro sign"],["&cent;","&#162;","cent sign"],["&pound;","&#163;","pound sign"],["&curren;","&#164;","currency sign"],["&yen;","&#165;","yen sign"],["&copy;","&#169;","copyright sign"],["&reg;","&#174;","registered sign"],["&trade;","&#8482;","trade mark sign"],["&permil;","&#8240;","per mille sign"],["&micro;",
"&#181;","micro sign"],["&middot;","&#183;","middle dot"],["&bull;","&#8226;","bullet"],["&hellip;","&#8230;","three dot leader"],["&prime;","&#8242;","minutes / feet"],["&Prime;","&#8243;","seconds / inches"],["&sect;","&#167;","section sign"],["&para;","&#182;","paragraph sign"],["&szlig;","&#223;","sharp s / ess-zed"],["&lsaquo;","&#8249;","single left-pointing angle quotation mark"],["&rsaquo;","&#8250;","single right-pointing angle quotation mark"],["&laquo;","&#171;","left pointing guillemet"],
["&raquo;","&#187;","right pointing guillemet"],["&lsquo;","&#8216;","left single quotation mark"],["&rsquo;","&#8217;","right single quotation mark"],["&ldquo;","&#8220;","left double quotation mark"],["&rdquo;","&#8221;","right double quotation mark"],["&bdquo;","&#8222;","double low-9 quotation mark"],["&le;","&#8804;","less-than or equal to"],["&ge;","&#8805;","greater-than or equal to"],["&ndash;","&#8211;","en dash"],["&mdash;","&#8212;","em dash"],["&macr;","&#175;","macron"],["&oline;","&#8254;",
"overline"],["&brvbar;","&#166;","broken bar"],["&iexcl;","&#161;","inverted exclamation mark"],["&iquest;","&#191;","turned question mark"],["&#9658;","&#9658;","triangle pointer"],["&tilde;","&#732;","small tilde"],["&deg;","&#176;","degree sign"],["&minus;","&#8722;","minus sign"],["&plusmn;","&#177;","plus-minus sign"],["&divide;","&#247;","division sign"],["&sup1;","&#185;","superscript one"],["&sup2;","&#178;","superscript two"],["&sup3;","&#179;","superscript three"],["&frac14;","&#188;","fraction one quarter"],
["&frac12;","&#189;","fraction one half"],["&frac34;","&#190;","fraction three quarters"],["&fnof;","&#402;","function / florin"],["&int;","&#8747;","integral"],["&sum;","&#8721;","n-ary sumation"],["&infin;","&#8734;","infinity"],["&radic;","&#8730;","square root"],["&asymp;","&#8776;","almost equal to"],["&ne;","&#8800;","not equal to"],["&equiv;","&#8801;","identical to"],["&prod;","&#8719;","n-ary product"],["&not;","&#172;","not sign"],["&cap;","&#8745;","intersection"],["&part;","&#8706;","partial differential"],
["&acute;","&#180;","acute accent"],["&ordf;","&#170;","feminine ordinal indicator"],["&ordm;","&#186;","masculine ordinal indicator"],["&dagger;","&#8224;","dagger"],["&Dagger;","&#8225;","double dagger"],["&Agrave;","&#192;","A - grave"],["&Aacute;","&#193;","A - acute"],["&Acirc;","&#194;","A - circumflex"],["&Atilde;","&#195;","A - tilde"],["&Auml;","&#196;","A - diaeresis"],["&Aring;","&#197;","A - ring above"],["&AElig;","&#198;","ligature AE"],["&Ccedil;","&#199;","C - cedilla"],["&Egrave;",
"&#200;","E - grave"],["&Eacute;","&#201;","E - acute"],["&Ecirc;","&#202;","E - circumflex"],["&Euml;","&#203;","E - diaeresis"],["&Igrave;","&#204;","I - grave"],["&Iacute;","&#205;","I - acute"],["&Icirc;","&#206;","I - circumflex"],["&Iuml;","&#207;","I - diaeresis"],["&ETH;","&#208;","ETH"],["&Ntilde;","&#209;","N - tilde"],["&Ograve;","&#210;","O - grave"],["&Oacute;","&#211;","O - acute"],["&Ocirc;","&#212;","O - circumflex"],["&Otilde;","&#213;","O - tilde"],["&Ouml;","&#214;","O - diaeresis"],
["&Oslash;","&#216;","O - slash"],["&OElig;","&#338;","ligature OE"],["&Scaron;","&#352;","S - caron"],["&Ugrave;","&#217;","U - grave"],["&Uacute;","&#218;","U - acute"],["&Ucirc;","&#219;","U - circumflex"],["&Uuml;","&#220;","U - diaeresis"],["&Yacute;","&#221;","Y - acute"],["&Yuml;","&#376;","Y - diaeresis"],["&THORN;","&#222;","THORN"],["&atilde;","&#227;","a - tilde"],["&auml;","&#228;","a - diaeresis"],["&aring;","&#229;","a - ring above"],["&aelig;","&#230;","ligature ae"],["&ccedil;","&#231;",
"c - cedilla"],["&euml;","&#235;","e - diaeresis"],["&igrave;","&#236;","i - grave"],["&iacute;","&#237;","i - acute"],["&icirc;","&#238;","i - circumflex"],["&iuml;","&#239;","i - diaeresis"],["&eth;","&#240;","eth"],["&ntilde;","&#241;","n - tilde"],["&ograve;","&#242;","o - grave"],["&oacute;","&#243;","o - acute"],["&ocirc;","&#244;","o - circumflex"],["&otilde;","&#245;","o - tilde"],["&ouml;","&#246;","o - diaeresis"],["&oslash;","&#248;","o slash"],["&oelig;","&#339;","ligature oe"],["&scaron;",
"&#353;","s - caron"],["&ugrave;","&#249;","u - grave"],["&uacute;","&#250;","u - acute"],["&ucirc;","&#251;","u - circumflex"],["&uuml;","&#252;","u - diaeresis"],["&yacute;","&#253;","y - acute"],["&thorn;","&#254;","thorn"],["&yuml;","&#255;","y - diaeresis"],["&Beta;","&#914;","Beta"],["&Gamma;","&#915;","Gamma"],["&Delta;","&#916;","Delta"],["&Epsilon;","&#917;","Epsilon"],["&Zeta;","&#918;","Zeta"],["&Eta;","&#919;","Eta"],["&Theta;","&#920;","Theta"],["&Iota;","&#921;","Iota"],["&Kappa;","&#922;",
"Kappa"],["&Lambda;","&#923;","Lambda"],["&Mu;","&#924;","Mu"],["&Nu;","&#925;","Nu"],["&Xi;","&#926;","Xi"],["&Omicron;","&#927;","Omicron"],["&Pi;","&#928;","Pi"],["&Rho;","&#929;","Rho"],["&Sigma;","&#931;","Sigma"],["&Tau;","&#932;","Tau"],["&Upsilon;","&#933;","Upsilon"],["&Phi;","&#934;","Phi"],["&Chi;","&#935;","Chi"],["&Psi;","&#936;","Psi"],["&Omega;","&#937;","Omega"],["&alpha;","&#945;","alpha"],["&beta;","&#946;","beta"],["&gamma;","&#947;","gamma"],["&delta;","&#948;","delta"],["&epsilon;",
"&#949;","epsilon"],["&zeta;","&#950;","zeta"],["&eta;","&#951;","eta"],["&theta;","&#952;","theta"],["&iota;","&#953;","iota"],["&kappa;","&#954;","kappa"],["&lambda;","&#955;","lambda"],["&mu;","&#956;","mu"],["&nu;","&#957;","nu"],["&xi;","&#958;","xi"],["&omicron;","&#959;","omicron"],["&pi;","&#960;","pi"],["&rho;","&#961;","rho"],["&sigmaf;","&#962;","final sigma"],["&sigma;","&#963;","sigma"],["&tau;","&#964;","tau"],["&upsilon;","&#965;","upsilon"],["&phi;","&#966;","phi"],["&chi;","&#967;",
"chi"],["&psi;","&#968;","psi"],["&omega;","&#969;","omega"],["&larr;","&#8592;","leftwards arrow"],["&uarr;","&#8593;","upwards arrow"],["&rarr;","&#8594;","rightwards arrow"],["&darr;","&#8595;","downwards arrow"],["&harr;","&#8596;","left right arrow"],["&loz;","&#9674;","lozenge"],["&spades;","&#9824;","black spade suit"],["&clubs;","&#9827;","black club suit"],["&hearts;","&#9829;","black heart suit"],["&diams;","&#9830;","black diamond suit"],["&cong;","&#8773;","approximately equal to"],["&sim;",
"&#8764;","similar to"],["&isin;","&#8712;","element of"],["&notin;","&#8713;","not an element of"],["&ni;","&#8715;","contains as member"],["&and;","&#8743;","logical and"],["&or;","&#8744;","logical or"],["&cup;","&#8746;","union"],["&forall;","&#8704;","for all"],["&exist;","&#8707;","there exists"],["&empty;","&#8709;","diameter"],["&nabla;","&#8711;","backward difference"],["&lowast;","&#8727;","asterisk operator"],["&prop;","&#8733;","proportional to"],["&ang;","&#8736;","angle"],["&Alpha;",
"&#913;","Alpha"],["&alefsym;","&#8501;","alef symbol"],["&piv;","&#982;","pi symbol"],["&real;","&#8476;","real part symbol"],["&thetasym;","&#977;","theta symbol"],["&upsih;","&#978;","upsilon - hook symbol"],["&weierp;","&#8472;","Weierstrass p"],["&image;","&#8465;","imaginary part"],["&crarr;","&#8629;","carriage return"],["&lArr;","&#8656;","leftwards double arrow"],["&uArr;","&#8657;","upwards double arrow"],["&rArr;","&#8658;","rightwards double arrow"],["&dArr;","&#8659;","downwards double arrow"],
["&hArr;","&#8660;","left right double arrow"],["&there4;","&#8756;","therefore"],["&sub;","&#8834;","subset of"],["&sup;","&#8835;","superset of"],["&nsub;","&#8836;","not a subset of"],["&sube;","&#8838;","subset of or equal to"],["&supe;","&#8839;","superset of or equal to"],["&oplus;","&#8853;","circled plus"],["&otimes;","&#8855;","circled times"],["&perp;","&#8869;","perpendicular"],["&sdot;","&#8901;","dot operator"],["&lceil;","&#8968;","left ceiling"],["&rceil;","&#8969;","right ceiling"],
["&lfloor;","&#8970;","left floor"],["&rfloor;","&#8971;","right floor"],["&lang;","&#9001;","left-pointing angle bracket"],["&rang;","&#9002;","right-pointing angle bracket"]],d=0,e='<div id="table-chars"><div class="row-chars">',g=0;g<c.length;g++)d==b&&(e+='</div><div class="row-chars">',d=0),e+='<span class="cell-chars" ><a name="char" title="'+c[g][2]+'">'+c[g][0]+"</a></span>",d++;return e+"</div></div>"};shoutbox.mouseChar=function(){a("#table-chars a[name=char]").each(function(){a(this).on({click:function(){shoutbox.shoutInsertText(a(this).html(),
!1)},mouseover:function(){shoutbox.zoomChar(a(this).html(),a(this).attr("title"))},mouseout:function(){shoutbox.zoomChar("","")}})})};shoutbox.zoomChar=function(b,c){a("#zoom").text(b);a("#zoom2").text(c)}})(jQuery);