imports:
    - { resource: tables.yml }

services:
    _defaults:
        public: true

    sylver35.breizhshoutbox.controller:
        class: sylver35\breizhshoutbox\controller\main
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.javascript'
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
            - '@request'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext%'

    sylver35.breizhshoutbox.admin.controller:
        class: sylver35\breizhshoutbox\controller\admin_controller
        arguments:
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.functions_admin'
            - '@config'
            - '@controller.helper'
            - '@ext.manager'
            - '@dbal.conn'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.main_listener:
        class: sylver35\breizhshoutbox\event\main_listener
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.events'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }

    sylver35.breizhshoutbox.shoutbox:
        class: sylver35\breizhshoutbox\core\shoutbox
        arguments:
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.robot'
            - '@sylver35.breizhshoutbox.javascript'
            - '@sylver35.breizhshoutbox.bbcodes'
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@path_helper'
            - '@dbal.conn'
            - '@pagination'
            - '@request'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
            - '@log'
            - '@service_container'
            - '@ext.manager'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.javascript:
        class: sylver35\breizhshoutbox\core\javascript
        arguments:
            - '@sylver35.breizhshoutbox.work'
            - '@config'
            - '@controller.helper'
            - '@path_helper'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.php_ext%'

    sylver35.breizhshoutbox.functions_ajax:
        class: sylver35\breizhshoutbox\core\functions_ajax
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.robot'
            - '@sylver35.breizhshoutbox.bbcodes'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '%core.root_path%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'

    sylver35.breizhshoutbox.smilies:
        class: sylver35\breizhshoutbox\core\smilies
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '%core.root_path%'

    sylver35.breizhshoutbox.actions:
        class: sylver35\breizhshoutbox\core\actions
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.robot'
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '%core.root_path%'

    sylver35.breizhshoutbox.work:
        class: sylver35\breizhshoutbox\core\work
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@language'
            - '@cache.driver'
            - '@ext.manager'
            - '@controller.helper'
            - '@path_helper'
            - '@service_container'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.robot:
        class: sylver35\breizhshoutbox\core\robot
        arguments:
            - '@sylver35.breizhshoutbox.work'
            - '@config'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '@dbal.conn'
            - '@cache.driver'
            - '@dispatcher'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'

    sylver35.breizhshoutbox.bbcodes:
        class: sylver35\breizhshoutbox\core\bbcodes
        arguments:
            - '@sylver35.breizhshoutbox.work'
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'

    sylver35.breizhshoutbox.events:
        class: sylver35\breizhshoutbox\core\events
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.robot'
            - '@config'
            - '@user'
            - '@auth'
            - '@language'
            - '@dbal.conn'
            - '@dispatcher'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'

    sylver35.breizhshoutbox.functions_admin:
        class: sylver35\breizhshoutbox\core\functions_admin
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.work'
            - '@sylver35.breizhshoutbox.robot'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@ext.manager'
            - '%core.root_path%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.controller.ajax:
        class: sylver35\breizhshoutbox\controller\ajax
        arguments:
            - '@sylver35.breizhshoutbox.functions_ajax'
            - '@sylver35.breizhshoutbox.smilies'
            - '@sylver35.breizhshoutbox.actions'

    _defaults:
        public: true