imports:
    - { resource: tables.yml }

services:
    _defaults:
        public: true

    sylver35.breizhshoutbox.controller:
        class: sylver35\breizhshoutbox\controller\main
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
            - '@request'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext%'

    sylver35.breizhshoutbox.admin.controller:
        class: sylver35\breizhshoutbox\controller\admin_controller
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@sylver35.breizhshoutbox.functions_admin'
            - '@config'
            - '@controller.helper'
            - '@ext.manager'
            - '@dbal.conn'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.main_listener:
        class: sylver35\breizhshoutbox\event\main_listener
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }

    sylver35.breizhshoutbox.shoutbox:
        class: sylver35\breizhshoutbox\core\shoutbox
        arguments:
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@path_helper'
            - '@dbal.conn'
            - '@pagination'
            - '@request'
            - '@template'
            - '@auth'
            - '@user'
            - '@language'
            - '@log'
            - '@service_container'
            - '@ext.manager'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.functions_ajax:
        class: sylver35\breizhshoutbox\core\functions_ajax
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '%core.root_path%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'
    sylver35.breizhshoutbox.functions_admin:
        class: sylver35\breizhshoutbox\core\functions_admin
        arguments:
            - '@sylver35.breizhshoutbox.shoutbox'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@ext.manager'
            - '%core.root_path%'
            - '%sylver35.breizhshoutbox.tables.shoutbox%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_priv%'
            - '%sylver35.breizhshoutbox.tables.shoutbox_rules%'

    sylver35.breizhshoutbox.controller.ajax:
        class: sylver35\breizhshoutbox\controller\ajax
        arguments:
            - '@sylver35.breizhshoutbox.functions_ajax'
            - '@request'

    _defaults:
        public: true